INSERT INTO `users`(`id`,
                    `name`,
                    `family`,
                    `username`,
                    `mobile`,
                    `email`,
                    `password`,
                    `created_at`,
                    `updated_at`)
VALUES (1,
        'مصطفی',
        'غلامی',
        'mostafa',
        '09365895522',
        'Mostafagholamidev@gmail.com',
        '$2y$10$Ae1qyE65oaeT6THFLHcNROPEMhAz6mnVhaJYmSPkKdq28de3tBHsG',
        '2019-08-20 00:00:00',
        '2019-08-20 00:00:00');
